// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cli.proto

#ifndef PROTOBUF_cli_2eproto__INCLUDED
#define PROTOBUF_cli_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace tinynet {
namespace raft {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_cli_2eproto();
void protobuf_AssignDesc_cli_2eproto();
void protobuf_ShutdownFile_cli_2eproto();

class GetLeaderReq;
class GetLeaderResp;

// ===================================================================

class GetLeaderReq : public ::google::protobuf::Message {
 public:
  GetLeaderReq();
  virtual ~GetLeaderReq();

  GetLeaderReq(const GetLeaderReq& from);

  inline GetLeaderReq& operator=(const GetLeaderReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetLeaderReq& default_instance();

  void Swap(GetLeaderReq* other);

  // implements Message ----------------------------------------------

  GetLeaderReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetLeaderReq& from);
  void MergeFrom(const GetLeaderReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:tinynet.raft.GetLeaderReq)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cli_2eproto();
  friend void protobuf_AssignDesc_cli_2eproto();
  friend void protobuf_ShutdownFile_cli_2eproto();

  void InitAsDefaultInstance();
  static GetLeaderReq* default_instance_;
};
// -------------------------------------------------------------------

class GetLeaderResp : public ::google::protobuf::Message {
 public:
  GetLeaderResp();
  virtual ~GetLeaderResp();

  GetLeaderResp(const GetLeaderResp& from);

  inline GetLeaderResp& operator=(const GetLeaderResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetLeaderResp& default_instance();

  void Swap(GetLeaderResp* other);

  // implements Message ----------------------------------------------

  GetLeaderResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetLeaderResp& from);
  void MergeFrom(const GetLeaderResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string leaderName = 1;
  inline bool has_leadername() const;
  inline void clear_leadername();
  static const int kLeaderNameFieldNumber = 1;
  inline const ::std::string& leadername() const;
  inline void set_leadername(const ::std::string& value);
  inline void set_leadername(const char* value);
  inline void set_leadername(const char* value, size_t size);
  inline ::std::string* mutable_leadername();
  inline ::std::string* release_leadername();
  inline void set_allocated_leadername(::std::string* leadername);

  // optional string leaderAddress = 2;
  inline bool has_leaderaddress() const;
  inline void clear_leaderaddress();
  static const int kLeaderAddressFieldNumber = 2;
  inline const ::std::string& leaderaddress() const;
  inline void set_leaderaddress(const ::std::string& value);
  inline void set_leaderaddress(const char* value);
  inline void set_leaderaddress(const char* value, size_t size);
  inline ::std::string* mutable_leaderaddress();
  inline ::std::string* release_leaderaddress();
  inline void set_allocated_leaderaddress(::std::string* leaderaddress);

  // @@protoc_insertion_point(class_scope:tinynet.raft.GetLeaderResp)
 private:
  inline void set_has_leadername();
  inline void clear_has_leadername();
  inline void set_has_leaderaddress();
  inline void clear_has_leaderaddress();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* leadername_;
  ::std::string* leaderaddress_;
  friend void  protobuf_AddDesc_cli_2eproto();
  friend void protobuf_AssignDesc_cli_2eproto();
  friend void protobuf_ShutdownFile_cli_2eproto();

  void InitAsDefaultInstance();
  static GetLeaderResp* default_instance_;
};
// ===================================================================

class RaftCliRpcService_Stub;

class RaftCliRpcService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline RaftCliRpcService() {};
 public:
  virtual ~RaftCliRpcService();

  typedef RaftCliRpcService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void GetLeader(::google::protobuf::RpcController* controller,
                       const ::tinynet::raft::GetLeaderReq* request,
                       ::tinynet::raft::GetLeaderResp* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(RaftCliRpcService);
};

class RaftCliRpcService_Stub : public RaftCliRpcService {
 public:
  RaftCliRpcService_Stub(::google::protobuf::RpcChannel* channel);
  RaftCliRpcService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~RaftCliRpcService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements RaftCliRpcService ------------------------------------------

  void GetLeader(::google::protobuf::RpcController* controller,
                       const ::tinynet::raft::GetLeaderReq* request,
                       ::tinynet::raft::GetLeaderResp* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(RaftCliRpcService_Stub);
};


// ===================================================================


// ===================================================================

// GetLeaderReq

// -------------------------------------------------------------------

// GetLeaderResp

// optional string leaderName = 1;
inline bool GetLeaderResp::has_leadername() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetLeaderResp::set_has_leadername() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetLeaderResp::clear_has_leadername() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetLeaderResp::clear_leadername() {
  if (leadername_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    leadername_->clear();
  }
  clear_has_leadername();
}
inline const ::std::string& GetLeaderResp::leadername() const {
  // @@protoc_insertion_point(field_get:tinynet.raft.GetLeaderResp.leaderName)
  return *leadername_;
}
inline void GetLeaderResp::set_leadername(const ::std::string& value) {
  set_has_leadername();
  if (leadername_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    leadername_ = new ::std::string;
  }
  leadername_->assign(value);
  // @@protoc_insertion_point(field_set:tinynet.raft.GetLeaderResp.leaderName)
}
inline void GetLeaderResp::set_leadername(const char* value) {
  set_has_leadername();
  if (leadername_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    leadername_ = new ::std::string;
  }
  leadername_->assign(value);
  // @@protoc_insertion_point(field_set_char:tinynet.raft.GetLeaderResp.leaderName)
}
inline void GetLeaderResp::set_leadername(const char* value, size_t size) {
  set_has_leadername();
  if (leadername_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    leadername_ = new ::std::string;
  }
  leadername_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:tinynet.raft.GetLeaderResp.leaderName)
}
inline ::std::string* GetLeaderResp::mutable_leadername() {
  set_has_leadername();
  if (leadername_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    leadername_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:tinynet.raft.GetLeaderResp.leaderName)
  return leadername_;
}
inline ::std::string* GetLeaderResp::release_leadername() {
  clear_has_leadername();
  if (leadername_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = leadername_;
    leadername_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void GetLeaderResp::set_allocated_leadername(::std::string* leadername) {
  if (leadername_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete leadername_;
  }
  if (leadername) {
    set_has_leadername();
    leadername_ = leadername;
  } else {
    clear_has_leadername();
    leadername_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:tinynet.raft.GetLeaderResp.leaderName)
}

// optional string leaderAddress = 2;
inline bool GetLeaderResp::has_leaderaddress() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GetLeaderResp::set_has_leaderaddress() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GetLeaderResp::clear_has_leaderaddress() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GetLeaderResp::clear_leaderaddress() {
  if (leaderaddress_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    leaderaddress_->clear();
  }
  clear_has_leaderaddress();
}
inline const ::std::string& GetLeaderResp::leaderaddress() const {
  // @@protoc_insertion_point(field_get:tinynet.raft.GetLeaderResp.leaderAddress)
  return *leaderaddress_;
}
inline void GetLeaderResp::set_leaderaddress(const ::std::string& value) {
  set_has_leaderaddress();
  if (leaderaddress_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    leaderaddress_ = new ::std::string;
  }
  leaderaddress_->assign(value);
  // @@protoc_insertion_point(field_set:tinynet.raft.GetLeaderResp.leaderAddress)
}
inline void GetLeaderResp::set_leaderaddress(const char* value) {
  set_has_leaderaddress();
  if (leaderaddress_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    leaderaddress_ = new ::std::string;
  }
  leaderaddress_->assign(value);
  // @@protoc_insertion_point(field_set_char:tinynet.raft.GetLeaderResp.leaderAddress)
}
inline void GetLeaderResp::set_leaderaddress(const char* value, size_t size) {
  set_has_leaderaddress();
  if (leaderaddress_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    leaderaddress_ = new ::std::string;
  }
  leaderaddress_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:tinynet.raft.GetLeaderResp.leaderAddress)
}
inline ::std::string* GetLeaderResp::mutable_leaderaddress() {
  set_has_leaderaddress();
  if (leaderaddress_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    leaderaddress_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:tinynet.raft.GetLeaderResp.leaderAddress)
  return leaderaddress_;
}
inline ::std::string* GetLeaderResp::release_leaderaddress() {
  clear_has_leaderaddress();
  if (leaderaddress_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = leaderaddress_;
    leaderaddress_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void GetLeaderResp::set_allocated_leaderaddress(::std::string* leaderaddress) {
  if (leaderaddress_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete leaderaddress_;
  }
  if (leaderaddress) {
    set_has_leaderaddress();
    leaderaddress_ = leaderaddress;
  } else {
    clear_has_leaderaddress();
    leaderaddress_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:tinynet.raft.GetLeaderResp.leaderAddress)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace raft
}  // namespace tinynet

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cli_2eproto__INCLUDED
