// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error_code.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "error_code.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace tinynet {

namespace {

const ::google::protobuf::EnumDescriptor* ErrorCode_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_error_5fcode_2eproto() {
  protobuf_AddDesc_error_5fcode_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "error_code.proto");
  GOOGLE_CHECK(file != NULL);
  ErrorCode_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_error_5fcode_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_error_5fcode_2eproto() {
}

void protobuf_AddDesc_error_5fcode_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020error_code.proto\022\007tinynet*\255\027\n\tErrorCod"
    "e\022\014\n\010ERROR_OK\020\000\022\031\n\014ERROR_FAILED\020\377\377\377\377\377\377\377\377"
    "\377\001\022\030\n\013ERROR_INVAL\020\352\377\377\377\377\377\377\377\377\001\022\031\n\014ERROR_OS"
    "_OOM\020\367\330\377\377\377\377\377\377\377\001\022!\n\024ERROR_OS_ADAPTERINFO\020"
    "\366\330\377\377\377\377\377\377\377\001\022#\n\026ERROR_URI_UNRECOGNIZED\020\305\330\377"
    "\377\377\377\377\377\377\001\022\"\n\025ERROR_NET_GETADDRINFO\020\223\330\377\377\377\377\377"
    "\377\377\001\022\036\n\021ERROR_SOCKET_BADF\020\257\327\377\377\377\377\377\377\377\001\022#\n\026E"
    "RROR_SOCKET_REUSEADDR\020\256\327\377\377\377\377\377\377\377\001\022#\n\026ERRO"
    "R_SOCKET_REUSEPORT\020\255\327\377\377\377\377\377\377\377\001\022%\n\030ERROR_S"
    "OCKET_SETIPV6ONLY\020\254\327\377\377\377\377\377\377\377\001\022\036\n\021ERROR_SO"
    "CKET_BIND\020\253\327\377\377\377\377\377\377\377\001\022 \n\023ERROR_SOCKET_LIS"
    "TEN\020\252\327\377\377\377\377\377\377\377\001\022 \n\023ERROR_SOCKET_ACCEPT\020\251\327"
    "\377\377\377\377\377\377\377\001\022(\n\033ERROR_SOCKET_SETNONBLOCKING\020"
    "\250\327\377\377\377\377\377\377\377\001\022&\n\031ERROR_SOCKET_CLOSEDBYPEER\020"
    "\247\327\377\377\377\377\377\377\377\001\022(\n\033ERROR_SOCKET_CLOSEDBYSERVE"
    "R\020\246\327\377\377\377\377\377\377\377\001\022\036\n\021ERROR_SOCKET_READ\020\245\327\377\377\377\377"
    "\377\377\377\001\022\037\n\022ERROR_SOCKET_WRITE\020\244\327\377\377\377\377\377\377\377\001\022\036\n"
    "\021ERROR_SOCKET_POLL\020\243\327\377\377\377\377\377\377\377\001\022!\n\024ERROR_S"
    "OCKET_CONNECT\020\242\327\377\377\377\377\377\377\377\001\022+\n\036ERROR_SOCKET"
    "_CONNECTIONREFUSED\020\241\327\377\377\377\377\377\377\377\001\022\'\n\032ERROR_S"
    "OCKET_BINDANDLISTEN\020\240\327\377\377\377\377\377\377\377\001\022&\n\031ERROR_"
    "UNIX_SOCKET_CONNECT\020\237\327\377\377\377\377\377\377\377\001\022%\n\030ERROR_"
    "SOCKET_GETSOCKNAME\020\236\327\377\377\377\377\377\377\377\001\022%\n\030ERROR_S"
    "OCKET_GETPEERNAME\020\235\327\377\377\377\377\377\377\377\001\022$\n\027ERROR_SO"
    "CKET_GETSOCKOPT\020\234\327\377\377\377\377\377\377\377\001\022\"\n\025ERROR_SOCK"
    "ET_READ_EOF\020\233\327\377\377\377\377\377\377\377\001\022\'\n\032ERROR_SOCKET_N"
    "OT_CONNECTED\020\232\327\377\377\377\377\377\377\377\001\022(\n\033ERROR_SOCKET_"
    "CONNECTTIMEOUT\020\231\327\377\377\377\377\377\377\377\001\022\'\n\032ERROR_SOCKE"
    "T_CONNECTCLOSED\020\230\327\377\377\377\377\377\377\377\001\022-\n ERROR_WEBS"
    "OCKET_KEEPALIVETIMEOUT\020\313\326\377\377\377\377\377\377\377\001\022-\n ERR"
    "OR_WEBSOCKET_HANDSHAKETIMEOUT\020\312\326\377\377\377\377\377\377\377\001"
    "\022&\n\031ERROR_WEBSOCKET_HANDSHAKE\020\311\326\377\377\377\377\377\377\377\001"
    "\022)\n\034ERROR_WEBSOCKET_CLOSEDBYPEER\020\310\326\377\377\377\377\377"
    "\377\377\001\022+\n\036ERROR_WEBSOCKET_CLOSEDBYSERVER\020\307\326"
    "\377\377\377\377\377\377\377\001\022+\n\036ERROR_WEBSOCKET_PAYLOAD_LENG"
    "TH\020\306\326\377\377\377\377\377\377\377\001\022\037\n\022ERROR_HTTP_REQUEST\020\267\326\377\377"
    "\377\377\377\377\377\001\022!\n\024ERROR_SERVER_STARTED\020\347\325\377\377\377\377\377\377\377"
    "\001\022%\n\030ERROR_EVENTLOOP_REGISTER\020\335\325\377\377\377\377\377\377\377\001"
    "\022$\n\027ERROR_RPC_SEQUENCEERROR\020\203\325\377\377\377\377\377\377\377\001\022$"
    "\n\027ERROR_RPC_CHECKSUMERROR\020\202\325\377\377\377\377\377\377\377\001\022#\n\026"
    "ERROR_RPC_CHANNELERROR\020\201\325\377\377\377\377\377\377\377\001\022%\n\030ERR"
    "OR_RPC_METHODNOTFOUND\020\200\325\377\377\377\377\377\377\377\001\022&\n\031ERRO"
    "R_RPC_REQUESTCANCELED\020\377\324\377\377\377\377\377\377\377\001\022\"\n\025ERRO"
    "R_RPC_ENCODEERROR\020\376\324\377\377\377\377\377\377\377\001\022\"\n\025ERROR_RP"
    "C_DECODEERROR\020\375\324\377\377\377\377\377\377\377\001\022%\n\030ERROR_RPC_ME"
    "SSAGETOOLONG\020\374\324\377\377\377\377\377\377\377\001\022\"\n\025ERROR_RAFT_NO"
    "SUCHNODE\020\237\324\377\377\377\377\377\377\377\001\022#\n\026ERROR_RAFT_CLUSTE"
    "RDOWN\020\236\324\377\377\377\377\377\377\377\001\022%\n\030ERROR_RAFT_CONFIGURA"
    "TION\020\235\324\377\377\377\377\377\377\377\001\022)\n\034ERROR_RAFT_SNAPSHOTLO"
    "ADERROR\020\234\324\377\377\377\377\377\377\377\001\022$\n\027ERROR_RAFT_WALLOAD"
    "ERROR\020\233\324\377\377\377\377\377\377\377\001\022\035\n\020ERROR_TNS_NOSTUB\020\273\323\377"
    "\377\377\377\377\377\377\001\022)\n\034ERROR_TNS_SERVICEUNAVAILABLE\020"
    "\272\323\377\377\377\377\377\377\377\001\022&\n\031ERROR_TNS_SERVICEREDIRECT\020"
    "\271\323\377\377\377\377\377\377\377\001\022\"\n\025ERROR_TNS_MAXREDIRECT\020\270\323\377\377"
    "\377\377\377\377\377\001\022#\n\026ERROR_TNS_NAMENOTFOUND\020\267\323\377\377\377\377\377"
    "\377\377\001\022)\n\034ERROR_TNS_UNRECOGNIZEDFORMAT\020\266\323\377\377"
    "\377\377\377\377\377\001\022\"\n\025ERROR_TNS_NAMEEXPIRED\020\265\323\377\377\377\377\377\377"
    "\377\001\022%\n\030ERROR_TNS_METHODNOTFOUND\020\264\323\377\377\377\377\377\377\377"
    "\001\022)\n\034ERROR_TDC_SERVICEUNAVAILABLE\020\327\322\377\377\377\377"
    "\377\377\377\001\022+\n\036ERROR_TDC_MESSAGEQUEUEOVERFLOW\020\326"
    "\322\377\377\377\377\377\377\377\001\022#\n\026ERROR_TDC_SERVICEMOVED\020\325\322\377\377"
    "\377\377\377\377\377\001\022+\n\036ERROR_TDC_MESSAGEOUTOFSEQUENCE"
    "\020\324\322\377\377\377\377\377\377\377\001\022\035\n\020ERROR_TDC_NOSTUB\020\323\322\377\377\377\377\377\377"
    "\377\001\022&\n\031ERROR_MYSQL_UNINITIALIZED\020\363\321\377\377\377\377\377\377"
    "\377\001\022(\n\033ERROR_MYSQL_PROTOCOLVERSION\020\362\321\377\377\377\377"
    "\377\377\377\001\022\'\n\032ERROR_MYSQL_CONNECTTIMEOUT\020\361\321\377\377\377"
    "\377\377\377\377\001\022\"\n\025ERROR_MYSQL_HANDSHAKE\020\360\321\377\377\377\377\377\377\377"
    "\001\022\"\n\025ERROR_MYSQL_QUERYBUSY\020\357\321\377\377\377\377\377\377\377\001\022&\n"
    "\031ERROR_MYSQL_READINGPACKET\020\356\321\377\377\377\377\377\377\377\001\022\'\n"
    "\032ERROR_REDIS_CONNECTTIMEOUT\020\301\321\377\377\377\377\377\377\377\001\022\""
    "\n\025ERROR_REDIS_HANDSHAKE\020\300\321\377\377\377\377\377\377\377\001\022%\n\030ER"
    "ROR_REDIS_READINGREPLY\020\277\321\377\377\377\377\377\377\377\001\022)\n\034ERR"
    "OR_REDIS_CONNECTIONCLOSED\020\276\321\377\377\377\377\377\377\377\001\022\"\n\025"
    "ERROR_REDIS_SUBSCRIBE\020\275\321\377\377\377\377\377\377\377\001\022 \n\023ERRO"
    "R_PROCESS_SPAWN\020\217\321\377\377\377\377\377\377\377\001\022\037\n\022ERROR_PROC"
    "ESS_KILL\020\216\321\377\377\377\377\377\377\377\001", 3019);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "error_code.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_error_5fcode_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_error_5fcode_2eproto {
  StaticDescriptorInitializer_error_5fcode_2eproto() {
    protobuf_AddDesc_error_5fcode_2eproto();
  }
} static_descriptor_initializer_error_5fcode_2eproto_;
const ::google::protobuf::EnumDescriptor* ErrorCode_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ErrorCode_descriptor_;
}
bool ErrorCode_IsValid(int value) {
  switch(value) {
    case -6002:
    case -6001:
    case -5955:
    case -5954:
    case -5953:
    case -5952:
    case -5951:
    case -5906:
    case -5905:
    case -5904:
    case -5903:
    case -5902:
    case -5901:
    case -5805:
    case -5804:
    case -5803:
    case -5802:
    case -5801:
    case -5708:
    case -5707:
    case -5706:
    case -5705:
    case -5704:
    case -5703:
    case -5702:
    case -5701:
    case -5605:
    case -5604:
    case -5603:
    case -5602:
    case -5601:
    case -5508:
    case -5507:
    case -5506:
    case -5505:
    case -5504:
    case -5503:
    case -5502:
    case -5501:
    case -5411:
    case -5401:
    case -5321:
    case -5306:
    case -5305:
    case -5304:
    case -5303:
    case -5302:
    case -5301:
    case -5224:
    case -5223:
    case -5222:
    case -5221:
    case -5220:
    case -5219:
    case -5218:
    case -5217:
    case -5216:
    case -5215:
    case -5214:
    case -5213:
    case -5212:
    case -5211:
    case -5210:
    case -5209:
    case -5208:
    case -5207:
    case -5206:
    case -5205:
    case -5204:
    case -5203:
    case -5202:
    case -5201:
    case -5101:
    case -5051:
    case -5002:
    case -5001:
    case -22:
    case -1:
    case 0:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace tinynet

// @@protoc_insertion_point(global_scope)
